//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamManagementSystem.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exams()
        {
            this.GradeSheets = new HashSet<GradeSheets>();
            this.Questions = new HashSet<Questions>();
        }
    
        public int Id { get; set; }
        public int SectionId { get; set; }
        public string ExamName { get; set; }
        public System.DateTime StartTime { get; set; }
        public int Duration { get; set; }
        public double TotalMarks { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Sections Sections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradeSheets> GradeSheets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Questions> Questions { get; set; }
    }
}
