//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamManagementSystem.Models.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExamManagementSystemDBEntities1 : DbContext
    {
        public ExamManagementSystemDBEntities1()
            : base("name=ExamManagementSystemDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<Enrolls> Enrolls { get; set; }
        public virtual DbSet<Exams> Exams { get; set; }
        public virtual DbSet<GradeSheets> GradeSheets { get; set; }
        public virtual DbSet<Options> Options { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<Sections> Sections { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<SubmittedAnswers> SubmittedAnswers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
