//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamManagementSystem.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmittedAnswer
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int QuestionId { get; set; }
        public int OptionBin { get; set; }
        public string AnswerText { get; set; }
        public int AttemptTime { get; set; }
        public double ObtaintedMarks { get; set; }
        public string Filepath { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Student Student { get; set; }
    }
}
